server {
    listen 80;
    listen [::]:80;
    server_name pay.teratech.co.tz;

    root /var/www/pay.teratech.co.tz;
    index callback.php;

    access_log /var/log/nginx/pay.teratech.co.tz.access.log;
    error_log  /var/log/nginx/pay.teratech.co.tz.error.log;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    location / {
        try_files $uri $uri/ /callback.php;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
    }

    location ~ /\. {
        deny all;
    }
}
